/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-111893-gbef151d-Reino"
#endif /* AVUTIL_FFVERSION_H */
